### PR TITLE
Handle empty alias group case

### LINKED ISSUE #360: Prow accepted invalid OWNERS_ALIASES change and broke approvals
# Issue

We use OWNERS file that points to aliases listed in OWNERS_ALIASES.

We promoted all of our reviewers to approvers in [this PR](https://github.com/metal3-io/ironic-standalone-operator/pull/116), which then caused Prow to stop accepting approves, such as [here](https://github.com/metal3-io/ironic-standalone-operator/pull/114) and [here](https://github.com/metal3-io/ironic-standalone-operator/pull/120).

## Expected outcome

When merging [PR116](https://github.com/metal3-io/ironic-standalone-operator/pull/116), Prow should've labeled the PR as "do-not-merge/invalid-owners-file" and blocked it.

## Actual outcome

Prow/tide did not complain, we merged it, and noticed that approving was broken. Had to manually merge a [fix PR](https://github.com/metal3-io/ironic-standalone-operator/pull/120), which then solved the situation right away.

Looking at the verify-owners_test.go:
1. It seems it should fail to empty groups. I'm suspecting there is loophole due usage of OWNERS_ALIASES, which is much less tested here. 
2. Another alternative is the use of `{}` to signal empty group, which is valid YAML, but maybe not expected by Prow?

## Logs

There was no error logs in Prow, just regular comment/approval handling logs, that did not indicate OWNERS was broken. It just claimed "comment did not result in approval".

### PR DESCRIPTION
**Pull request by nikhilnishad-goog**
For this [issue](https://github.com/kubernetes-sigs/prow/issues/360). Modifies repoowners.go to handle cases where the file has an alias group but does not have any user name listed in it. 

There are multiple acceptable yamls that are being not parsed explictly and edge cases not handled. Examples are -

```
aliases:
  alias-group:
```

```
aliases:
  alias-group: {}
```

```
aliases:
  alias-group: {alias1, alias2}
```

```
aliases:
  alias-group: ""
```

All of these are valid yamls, that can cause silent failures like the one mentioned in #360 .

Fixes #360

### CODE REVIEW

File: pkg/plugins/verify-owners/verify-owners_test.go [hunk 1]
```diff
@@ -832,6 +832,11 @@ var ownersAliases = map[string][]byte{
 	"collaborators": []byte(`aliases:
   foo-reviewers:
   - alice
+`),
+	"emptyAliasGroupOwnersAliases": []byte(`aliases:
```
Comment (tuminoid) [inline pkg/plugins/verify-owners/verify-owners_test.go:836]: Should we also test here the non-braces version, or does that get caught somewhere else already?

File: pkg/repoowners/repoowners_test.go [hunk 2]
```diff
@@ -1427,3 +1427,63 @@ func TestRepoOwners_AllReviewers(t *testing.T) {
...
+            if (err != nil) != tt.wantErr {
+                t.Errorf("ParseAliasesConfig() error = %v, wantErr %v", err, tt.wantErr)
+                return
+            }
+            if !reflect.DeepEqual(got, tt.expected) {
+                t.Errorf("ParseAliasesConfig() = %v, want %v", got, tt.expected)
+            }
+        })
+    }
+}
```
Comment (tuminoid) [inline pkg/repoowners/repoowners_test.go:1489]: Nit: missing final EOL.

File: pkg/plugins/verify-owners/verify-owners_test.go [hunk 3]
```diff
@@ -1435,3 +1440,109 @@ func testOwnersRemoval(clients localgit.Clients, t *testing.T) {
...
+			name:                 "empty alias group additions in OWNERS_ALIASES file",
+			filesChanged:         []string{"OWNERS_ALIASES"},
+			ownersFile:           "collaboratorsWithAliases",
+			ownersAliasesFile:    "emptyAliasGroupOwnersAliases",
+			shouldError:          true,
+			expectedErrorMessage: "error parsing aliases config for OWNERS_ALIASES file",
+			skipTrustedUserCheck: true,
+		},
+	}
+	lg, c, err := clients()
```
Comment (tuminoid) [inline pkg/plugins/verify-owners/verify-owners_test.go:1468]: Nit: separate the test case definitions from the code with empty line.

File: pkg/repoowners/repoowners_test.go [hunk 4]
```diff
@@ -1427,3 +1427,63 @@ func TestRepoOwners_AllReviewers(t *testing.T) {
...
+        },
+        {
+            name: "empty alias group with braces",
+            input: `
+aliases:
+  empty-alias-group-with-braces: {}
+`,
+            expected: RepoAliases{},
+            wantErr:  true,
+			errContains: "alias group is empty",
```
Comment (tuminoid) [inline pkg/repoowners/repoowners_test.go:1463]: These `errContains` are not used for anything?

**Review by tuminoid — COMMENTED** [review]
Thanks for taking a look! 

Took initial look at this, mostly nits.

I'm also thinking if we really should error out in unmarshalling the aliases, or just gracefully accept a group was empty and did not add any usernames. As a user, I'd kinda hate the fact that if I don't have any people left in a group, I'd need to comment out the alias and everywhere it is referred.

**Comment by nikhilnishad-goog** [comment]
@tuminoid  Thanks for taking a look.

> I'm also thinking if we really should error out in unmarshalling the aliases, or just gracefully accept a group was empty and did not add any usernames. As a user, I'd kinda hate the fact that if I don't have any people left in a group, I'd need to comment out the alias and everywhere it is referred.

I am in the opinion of throwing when unmarshalling, ideally, there should be no dead code (which includes empty groups that are not meant to have any effect anywhere). The tests should match that behavior.

Also, there are some missed cases, i will update the PR soon.

File: pkg/repoowners/repoowners.go [hunk 5]
```diff
@@ -663,14 +663,45 @@ func ParseAliasesConfig(b []byte) (RepoAliases, error) {
...
 	}
 
 	for alias, expanded := range config.Data {
-		result[github.NormLogin(alias)] = NormLogins(expanded)
+		switch v := expanded.(type) {
+		case []interface{}:
+			// Convert []interface{} to []string
+			var members []string
+			for _, member := range v {
+				members = append(members, member.(string))
```
Comment (jmguzik) [inline pkg/repoowners/repoowners.go:678]:
```suggestion
			str, ok := member.(string)
			if !ok {
				return result, fmt.Errorf("alias group '%s' contains a non-string value", alias)
			}
```
type check here?

**Review by tuminoid — COMMENTED** [review]
Can you squash the commits? Otherwise LGTM.

File: pkg/repoowners/repoowners.go [hunk 6]
```diff
@@ -663,14 +663,49 @@ func ParseAliasesConfig(b []byte) (RepoAliases, error) {
...
+		case map[string]interface{}:
+			// Handle Flow Style Mapping (Inline Dictionary/Object Syntax). Example - aliases: { alias-group: { alias1, alias2 } }
+			if len(v) == 0 {
+				return result, fmt.Errorf("alias group '%s' is empty", alias)
+			}
+			var members []string
+            for key := range v {
+				members = append(members, key)
+            }
+            result[github.NormLogin(alias)] = NormLogins(members)
```
Comment (petr-muller) [inline pkg/repoowners/repoowners.go:702]: nit: weird indent here (how do we not have a gofmt job lol)

File: pkg/repoowners/repoowners.go [hunk 7]
```diff
@@ -663,14 +663,49 @@ func ParseAliasesConfig(b []byte) (RepoAliases, error) {
...
+			}
+			if len(members) == 0 {
+				return result, fmt.Errorf("alias group '%s' is empty", alias)
+			}
+			result[github.NormLogin(alias)] = NormLogins(members)
+		case string:
+			// Handle empty string as an empty list
+			if v == "" {
+				return result, fmt.Errorf("alias group '%s' is empty", alias)
+			}
```
Comment (petr-muller) [inline pkg/repoowners/repoowners.go:692]: we should never see a non-empty string here, right? If so can we hint code readers about that with a godoc, and/or maybe even either remove the conditional or add a "weird thing should not happen" error return?

File: pkg/plugins/verify-owners/verify-owners_test.go [hunk 8]
```diff
@@ -1435,3 +1445,119 @@ func testOwnersRemoval(clients localgit.Clients, t *testing.T) {
...
+			froc := makeFakeRepoOwnersClient()
+
+			prInfo := info{
+				org:          "org",
+				repo:         "repo",
+				repoFullName: "org/repo",
+				number:       pr,
+			}
+
+			if test.shouldError {
```
Comment (petr-muller) [inline pkg/plugins/verify-owners/verify-owners_test.go:1552]: if this is false then we don't test anything, which is unexpected for anyone who adds a `shouldError: false` test. Let's just remove this test param and this conditional? The test is called `testHandleParseAliasesConfigErrors` so it kinda implies that all tests expect errors.

**Review by petr-muller — APPROVED** [review]
Thanks!

**Comment by petr-muller** [comment]
This broke `approve` in repos where `OWNERS_ALIASES` had at least one empty alias, and actually it even broke `verify-owners` plugin :grimacing: I should have reviewed this better before approving, sorry.

We'll need to revert and figure out a better fix.

**Comment by nikhilnishad-goog** [comment]
Created another PR -> https://github.com/kubernetes-sigs/prow/pull/390 , changed how we handle empty aliases (simple PR comment instead of throwing errors).
